// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Reensef/go-microservices-course/inventory/internal/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPartRepository creates a new instance of MockPartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPartRepository {
	mock := &MockPartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPartRepository is an autogenerated mock type for the PartRepository type
type MockPartRepository struct {
	mock.Mock
}

type MockPartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPartRepository) EXPECT() *MockPartRepository_Expecter {
	return &MockPartRepository_Expecter{mock: &_m.Mock}
}

// GetByFilter provides a mock function for the type MockPartRepository
func (_mock *MockPartRepository) GetByFilter(ctx context.Context, filter *model.PartsFilter) []*model.Part {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetByFilter")
	}

	var r0 []*model.Part
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.PartsFilter) []*model.Part); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}
	return r0
}

// MockPartRepository_GetByFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByFilter'
type MockPartRepository_GetByFilter_Call struct {
	*mock.Call
}

// GetByFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *model.PartsFilter
func (_e *MockPartRepository_Expecter) GetByFilter(ctx interface{}, filter interface{}) *MockPartRepository_GetByFilter_Call {
	return &MockPartRepository_GetByFilter_Call{Call: _e.mock.On("GetByFilter", ctx, filter)}
}

func (_c *MockPartRepository_GetByFilter_Call) Run(run func(ctx context.Context, filter *model.PartsFilter)) *MockPartRepository_GetByFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.PartsFilter
		if args[1] != nil {
			arg1 = args[1].(*model.PartsFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPartRepository_GetByFilter_Call) Return(parts []*model.Part) *MockPartRepository_GetByFilter_Call {
	_c.Call.Return(parts)
	return _c
}

func (_c *MockPartRepository_GetByFilter_Call) RunAndReturn(run func(ctx context.Context, filter *model.PartsFilter) []*model.Part) *MockPartRepository_GetByFilter_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUuid provides a mock function for the type MockPartRepository
func (_mock *MockPartRepository) GetByUuid(ctx context.Context, uuid1 uuid.UUID) (*model.Part, error) {
	ret := _mock.Called(ctx, uuid1)

	if len(ret) == 0 {
		panic("no return value specified for GetByUuid")
	}

	var r0 *model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Part, error)); ok {
		return returnFunc(ctx, uuid1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Part); ok {
		r0 = returnFunc(ctx, uuid1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, uuid1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPartRepository_GetByUuid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUuid'
type MockPartRepository_GetByUuid_Call struct {
	*mock.Call
}

// GetByUuid is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid1 uuid.UUID
func (_e *MockPartRepository_Expecter) GetByUuid(ctx interface{}, uuid1 interface{}) *MockPartRepository_GetByUuid_Call {
	return &MockPartRepository_GetByUuid_Call{Call: _e.mock.On("GetByUuid", ctx, uuid1)}
}

func (_c *MockPartRepository_GetByUuid_Call) Run(run func(ctx context.Context, uuid1 uuid.UUID)) *MockPartRepository_GetByUuid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPartRepository_GetByUuid_Call) Return(part *model.Part, err error) *MockPartRepository_GetByUuid_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *MockPartRepository_GetByUuid_Call) RunAndReturn(run func(ctx context.Context, uuid1 uuid.UUID) (*model.Part, error)) *MockPartRepository_GetByUuid_Call {
	_c.Call.Return(run)
	return _c
}
