// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Reensef/go-microservices-course/notification/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotificationService creates a new instance of MockNotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationService {
	mock := &MockNotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationService is an autogenerated mock type for the NotificationService type
type MockNotificationService struct {
	mock.Mock
}

type MockNotificationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationService) EXPECT() *MockNotificationService_Expecter {
	return &MockNotificationService_Expecter{mock: &_m.Mock}
}

// NotifyOrderPaid provides a mock function for the type MockNotificationService
func (_mock *MockNotificationService) NotifyOrderPaid(ctx context.Context, event model.OrderPaidEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for NotifyOrderPaid")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.OrderPaidEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationService_NotifyOrderPaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyOrderPaid'
type MockNotificationService_NotifyOrderPaid_Call struct {
	*mock.Call
}

// NotifyOrderPaid is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.OrderPaidEvent
func (_e *MockNotificationService_Expecter) NotifyOrderPaid(ctx interface{}, event interface{}) *MockNotificationService_NotifyOrderPaid_Call {
	return &MockNotificationService_NotifyOrderPaid_Call{Call: _e.mock.On("NotifyOrderPaid", ctx, event)}
}

func (_c *MockNotificationService_NotifyOrderPaid_Call) Run(run func(ctx context.Context, event model.OrderPaidEvent)) *MockNotificationService_NotifyOrderPaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.OrderPaidEvent
		if args[1] != nil {
			arg1 = args[1].(model.OrderPaidEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationService_NotifyOrderPaid_Call) Return(err error) *MockNotificationService_NotifyOrderPaid_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationService_NotifyOrderPaid_Call) RunAndReturn(run func(ctx context.Context, event model.OrderPaidEvent) error) *MockNotificationService_NotifyOrderPaid_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyShipAssembled provides a mock function for the type MockNotificationService
func (_mock *MockNotificationService) NotifyShipAssembled(ctx context.Context, event model.ShipAssembledEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for NotifyShipAssembled")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ShipAssembledEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationService_NotifyShipAssembled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyShipAssembled'
type MockNotificationService_NotifyShipAssembled_Call struct {
	*mock.Call
}

// NotifyShipAssembled is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.ShipAssembledEvent
func (_e *MockNotificationService_Expecter) NotifyShipAssembled(ctx interface{}, event interface{}) *MockNotificationService_NotifyShipAssembled_Call {
	return &MockNotificationService_NotifyShipAssembled_Call{Call: _e.mock.On("NotifyShipAssembled", ctx, event)}
}

func (_c *MockNotificationService_NotifyShipAssembled_Call) Run(run func(ctx context.Context, event model.ShipAssembledEvent)) *MockNotificationService_NotifyShipAssembled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ShipAssembledEvent
		if args[1] != nil {
			arg1 = args[1].(model.ShipAssembledEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationService_NotifyShipAssembled_Call) Return(err error) *MockNotificationService_NotifyShipAssembled_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationService_NotifyShipAssembled_Call) RunAndReturn(run func(ctx context.Context, event model.ShipAssembledEvent) error) *MockNotificationService_NotifyShipAssembled_Call {
	_c.Call.Return(run)
	return _c
}
