// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Reensef/go-microservices-course/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentServiceClient creates a new instance of MockPaymentServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentServiceClient {
	mock := &MockPaymentServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentServiceClient is an autogenerated mock type for the PaymentServiceClient type
type MockPaymentServiceClient struct {
	mock.Mock
}

type MockPaymentServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentServiceClient) EXPECT() *MockPaymentServiceClient_Expecter {
	return &MockPaymentServiceClient_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function for the type MockPaymentServiceClient
func (_mock *MockPaymentServiceClient) PayOrder(ctx context.Context, orderUuid string, userUuid string, paymentMethod model.OrderPaymentMethod) (*string, error) {
	ret := _mock.Called(ctx, orderUuid, userUuid, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, model.OrderPaymentMethod) (*string, error)); ok {
		return returnFunc(ctx, orderUuid, userUuid, paymentMethod)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, model.OrderPaymentMethod) *string); ok {
		r0 = returnFunc(ctx, orderUuid, userUuid, paymentMethod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, model.OrderPaymentMethod) error); ok {
		r1 = returnFunc(ctx, orderUuid, userUuid, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentServiceClient_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type MockPaymentServiceClient_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUuid string
//   - userUuid string
//   - paymentMethod model.OrderPaymentMethod
func (_e *MockPaymentServiceClient_Expecter) PayOrder(ctx interface{}, orderUuid interface{}, userUuid interface{}, paymentMethod interface{}) *MockPaymentServiceClient_PayOrder_Call {
	return &MockPaymentServiceClient_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, orderUuid, userUuid, paymentMethod)}
}

func (_c *MockPaymentServiceClient_PayOrder_Call) Run(run func(ctx context.Context, orderUuid string, userUuid string, paymentMethod model.OrderPaymentMethod)) *MockPaymentServiceClient_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 model.OrderPaymentMethod
		if args[3] != nil {
			arg3 = args[3].(model.OrderPaymentMethod)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPaymentServiceClient_PayOrder_Call) Return(transactionUuid *string, err error) *MockPaymentServiceClient_PayOrder_Call {
	_c.Call.Return(transactionUuid, err)
	return _c
}

func (_c *MockPaymentServiceClient_PayOrder_Call) RunAndReturn(run func(ctx context.Context, orderUuid string, userUuid string, paymentMethod model.OrderPaymentMethod) (*string, error)) *MockPaymentServiceClient_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
