// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSaramaSyncProducer creates a new instance of MockSaramaSyncProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSaramaSyncProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSaramaSyncProducer {
	mock := &MockSaramaSyncProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSaramaSyncProducer is an autogenerated mock type for the SaramaSyncProducer type
type MockSaramaSyncProducer struct {
	mock.Mock
}

type MockSaramaSyncProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSaramaSyncProducer) EXPECT() *MockSaramaSyncProducer_Expecter {
	return &MockSaramaSyncProducer_Expecter{mock: &_m.Mock}
}

// SendMessage provides a mock function for the type MockSaramaSyncProducer
func (_mock *MockSaramaSyncProducer) SendMessage(msg *sarama.ProducerMessage) (int32, int64, error) {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 int32
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(*sarama.ProducerMessage) (int32, int64, error)); ok {
		return returnFunc(msg)
	}
	if returnFunc, ok := ret.Get(0).(func(*sarama.ProducerMessage) int32); ok {
		r0 = returnFunc(msg)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(*sarama.ProducerMessage) int64); ok {
		r1 = returnFunc(msg)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(*sarama.ProducerMessage) error); ok {
		r2 = returnFunc(msg)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSaramaSyncProducer_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockSaramaSyncProducer_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - msg *sarama.ProducerMessage
func (_e *MockSaramaSyncProducer_Expecter) SendMessage(msg interface{}) *MockSaramaSyncProducer_SendMessage_Call {
	return &MockSaramaSyncProducer_SendMessage_Call{Call: _e.mock.On("SendMessage", msg)}
}

func (_c *MockSaramaSyncProducer_SendMessage_Call) Run(run func(msg *sarama.ProducerMessage)) *MockSaramaSyncProducer_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sarama.ProducerMessage
		if args[0] != nil {
			arg0 = args[0].(*sarama.ProducerMessage)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSaramaSyncProducer_SendMessage_Call) Return(partition int32, offset int64, err error) *MockSaramaSyncProducer_SendMessage_Call {
	_c.Call.Return(partition, offset, err)
	return _c
}

func (_c *MockSaramaSyncProducer_SendMessage_Call) RunAndReturn(run func(msg *sarama.ProducerMessage) (int32, int64, error)) *MockSaramaSyncProducer_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}
