// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotificationConsumerConfig creates a new instance of MockNotificationConsumerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationConsumerConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationConsumerConfig {
	mock := &MockNotificationConsumerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationConsumerConfig is an autogenerated mock type for the NotificationConsumerConfig type
type MockNotificationConsumerConfig struct {
	mock.Mock
}

type MockNotificationConsumerConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationConsumerConfig) EXPECT() *MockNotificationConsumerConfig_Expecter {
	return &MockNotificationConsumerConfig_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockNotificationConsumerConfig
func (_mock *MockNotificationConsumerConfig) Config() *sarama.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *sarama.Config
	if returnFunc, ok := ret.Get(0).(func() *sarama.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sarama.Config)
		}
	}
	return r0
}

// MockNotificationConsumerConfig_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockNotificationConsumerConfig_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockNotificationConsumerConfig_Expecter) Config() *MockNotificationConsumerConfig_Config_Call {
	return &MockNotificationConsumerConfig_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockNotificationConsumerConfig_Config_Call) Run(run func()) *MockNotificationConsumerConfig_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotificationConsumerConfig_Config_Call) Return(config *sarama.Config) *MockNotificationConsumerConfig_Config_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *MockNotificationConsumerConfig_Config_Call) RunAndReturn(run func() *sarama.Config) *MockNotificationConsumerConfig_Config_Call {
	_c.Call.Return(run)
	return _c
}

// GroupID provides a mock function for the type MockNotificationConsumerConfig
func (_mock *MockNotificationConsumerConfig) GroupID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GroupID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockNotificationConsumerConfig_GroupID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GroupID'
type MockNotificationConsumerConfig_GroupID_Call struct {
	*mock.Call
}

// GroupID is a helper method to define mock.On call
func (_e *MockNotificationConsumerConfig_Expecter) GroupID() *MockNotificationConsumerConfig_GroupID_Call {
	return &MockNotificationConsumerConfig_GroupID_Call{Call: _e.mock.On("GroupID")}
}

func (_c *MockNotificationConsumerConfig_GroupID_Call) Run(run func()) *MockNotificationConsumerConfig_GroupID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotificationConsumerConfig_GroupID_Call) Return(s string) *MockNotificationConsumerConfig_GroupID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockNotificationConsumerConfig_GroupID_Call) RunAndReturn(run func() string) *MockNotificationConsumerConfig_GroupID_Call {
	_c.Call.Return(run)
	return _c
}

// OrderPaidTopic provides a mock function for the type MockNotificationConsumerConfig
func (_mock *MockNotificationConsumerConfig) OrderPaidTopic() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OrderPaidTopic")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockNotificationConsumerConfig_OrderPaidTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderPaidTopic'
type MockNotificationConsumerConfig_OrderPaidTopic_Call struct {
	*mock.Call
}

// OrderPaidTopic is a helper method to define mock.On call
func (_e *MockNotificationConsumerConfig_Expecter) OrderPaidTopic() *MockNotificationConsumerConfig_OrderPaidTopic_Call {
	return &MockNotificationConsumerConfig_OrderPaidTopic_Call{Call: _e.mock.On("OrderPaidTopic")}
}

func (_c *MockNotificationConsumerConfig_OrderPaidTopic_Call) Run(run func()) *MockNotificationConsumerConfig_OrderPaidTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotificationConsumerConfig_OrderPaidTopic_Call) Return(s string) *MockNotificationConsumerConfig_OrderPaidTopic_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockNotificationConsumerConfig_OrderPaidTopic_Call) RunAndReturn(run func() string) *MockNotificationConsumerConfig_OrderPaidTopic_Call {
	_c.Call.Return(run)
	return _c
}

// ShipAssembledTopic provides a mock function for the type MockNotificationConsumerConfig
func (_mock *MockNotificationConsumerConfig) ShipAssembledTopic() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShipAssembledTopic")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockNotificationConsumerConfig_ShipAssembledTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShipAssembledTopic'
type MockNotificationConsumerConfig_ShipAssembledTopic_Call struct {
	*mock.Call
}

// ShipAssembledTopic is a helper method to define mock.On call
func (_e *MockNotificationConsumerConfig_Expecter) ShipAssembledTopic() *MockNotificationConsumerConfig_ShipAssembledTopic_Call {
	return &MockNotificationConsumerConfig_ShipAssembledTopic_Call{Call: _e.mock.On("ShipAssembledTopic")}
}

func (_c *MockNotificationConsumerConfig_ShipAssembledTopic_Call) Run(run func()) *MockNotificationConsumerConfig_ShipAssembledTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNotificationConsumerConfig_ShipAssembledTopic_Call) Return(s string) *MockNotificationConsumerConfig_ShipAssembledTopic_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockNotificationConsumerConfig_ShipAssembledTopic_Call) RunAndReturn(run func() string) *MockNotificationConsumerConfig_ShipAssembledTopic_Call {
	_c.Call.Return(run)
	return _c
}
