// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTelegramConfig creates a new instance of MockTelegramConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTelegramConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTelegramConfig {
	mock := &MockTelegramConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTelegramConfig is an autogenerated mock type for the TelegramConfig type
type MockTelegramConfig struct {
	mock.Mock
}

type MockTelegramConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTelegramConfig) EXPECT() *MockTelegramConfig_Expecter {
	return &MockTelegramConfig_Expecter{mock: &_m.Mock}
}

// BotToken provides a mock function for the type MockTelegramConfig
func (_mock *MockTelegramConfig) BotToken() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BotToken")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTelegramConfig_BotToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BotToken'
type MockTelegramConfig_BotToken_Call struct {
	*mock.Call
}

// BotToken is a helper method to define mock.On call
func (_e *MockTelegramConfig_Expecter) BotToken() *MockTelegramConfig_BotToken_Call {
	return &MockTelegramConfig_BotToken_Call{Call: _e.mock.On("BotToken")}
}

func (_c *MockTelegramConfig_BotToken_Call) Run(run func()) *MockTelegramConfig_BotToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTelegramConfig_BotToken_Call) Return(s string) *MockTelegramConfig_BotToken_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTelegramConfig_BotToken_Call) RunAndReturn(run func() string) *MockTelegramConfig_BotToken_Call {
	_c.Call.Return(run)
	return _c
}

// ChatID provides a mock function for the type MockTelegramConfig
func (_mock *MockTelegramConfig) ChatID() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChatID")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockTelegramConfig_ChatID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChatID'
type MockTelegramConfig_ChatID_Call struct {
	*mock.Call
}

// ChatID is a helper method to define mock.On call
func (_e *MockTelegramConfig_Expecter) ChatID() *MockTelegramConfig_ChatID_Call {
	return &MockTelegramConfig_ChatID_Call{Call: _e.mock.On("ChatID")}
}

func (_c *MockTelegramConfig_ChatID_Call) Run(run func()) *MockTelegramConfig_ChatID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTelegramConfig_ChatID_Call) Return(n int64) *MockTelegramConfig_ChatID_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockTelegramConfig_ChatID_Call) RunAndReturn(run func() int64) *MockTelegramConfig_ChatID_Call {
	_c.Call.Return(run)
	return _c
}
