// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Reensef/go-microservices-course/payment/internal/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentService creates a new instance of MockPaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentService {
	mock := &MockPaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentService is an autogenerated mock type for the PaymentService type
type MockPaymentService struct {
	mock.Mock
}

type MockPaymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentService) EXPECT() *MockPaymentService_Expecter {
	return &MockPaymentService_Expecter{mock: &_m.Mock}
}

// Pay provides a mock function for the type MockPaymentService
func (_mock *MockPaymentService) Pay(ctx context.Context, orderUuid uuid.UUID, userUuid uuid.UUID, paymentMethod model.PaymentMethod) (*uuid.UUID, error) {
	ret := _mock.Called(ctx, orderUuid, userUuid, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for Pay")
	}

	var r0 *uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.PaymentMethod) (*uuid.UUID, error)); ok {
		return returnFunc(ctx, orderUuid, userUuid, paymentMethod)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.PaymentMethod) *uuid.UUID); ok {
		r0 = returnFunc(ctx, orderUuid, userUuid, paymentMethod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, model.PaymentMethod) error); ok {
		r1 = returnFunc(ctx, orderUuid, userUuid, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentService_Pay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pay'
type MockPaymentService_Pay_Call struct {
	*mock.Call
}

// Pay is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUuid uuid.UUID
//   - userUuid uuid.UUID
//   - paymentMethod model.PaymentMethod
func (_e *MockPaymentService_Expecter) Pay(ctx interface{}, orderUuid interface{}, userUuid interface{}, paymentMethod interface{}) *MockPaymentService_Pay_Call {
	return &MockPaymentService_Pay_Call{Call: _e.mock.On("Pay", ctx, orderUuid, userUuid, paymentMethod)}
}

func (_c *MockPaymentService_Pay_Call) Run(run func(ctx context.Context, orderUuid uuid.UUID, userUuid uuid.UUID, paymentMethod model.PaymentMethod)) *MockPaymentService_Pay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 model.PaymentMethod
		if args[3] != nil {
			arg3 = args[3].(model.PaymentMethod)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPaymentService_Pay_Call) Return(uUID *uuid.UUID, err error) *MockPaymentService_Pay_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockPaymentService_Pay_Call) RunAndReturn(run func(ctx context.Context, orderUuid uuid.UUID, userUuid uuid.UUID, paymentMethod model.PaymentMethod) (*uuid.UUID, error)) *MockPaymentService_Pay_Call {
	_c.Call.Return(run)
	return _c
}
