// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Reensef/go-microservices-course/iam/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(ctx context.Context, login string, password string) (*model.Session, error) {
	ret := _mock.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *model.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.Session, error)); ok {
		return returnFunc(ctx, login, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.Session); ok {
		r0 = returnFunc(ctx, login, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, login, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
func (_e *MockAuthService_Expecter) Login(ctx interface{}, login interface{}, password interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, login, password)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, login string, password string)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(session *model.Session, err error) *MockAuthService_Login_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(ctx context.Context, login string, password string) (*model.Session, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Whoami provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Whoami(ctx context.Context, sessionUuid string) (*model.Session, *model.User, error) {
	ret := _mock.Called(ctx, sessionUuid)

	if len(ret) == 0 {
		panic("no return value specified for Whoami")
	}

	var r0 *model.Session
	var r1 *model.User
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Session, *model.User, error)); ok {
		return returnFunc(ctx, sessionUuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Session); ok {
		r0 = returnFunc(ctx, sessionUuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *model.User); ok {
		r1 = returnFunc(ctx, sessionUuid)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, sessionUuid)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuthService_Whoami_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Whoami'
type MockAuthService_Whoami_Call struct {
	*mock.Call
}

// Whoami is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionUuid string
func (_e *MockAuthService_Expecter) Whoami(ctx interface{}, sessionUuid interface{}) *MockAuthService_Whoami_Call {
	return &MockAuthService_Whoami_Call{Call: _e.mock.On("Whoami", ctx, sessionUuid)}
}

func (_c *MockAuthService_Whoami_Call) Run(run func(ctx context.Context, sessionUuid string)) *MockAuthService_Whoami_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Whoami_Call) Return(session *model.Session, user *model.User, err error) *MockAuthService_Whoami_Call {
	_c.Call.Return(session, user, err)
	return _c
}

func (_c *MockAuthService_Whoami_Call) RunAndReturn(run func(ctx context.Context, sessionUuid string) (*model.Session, *model.User, error)) *MockAuthService_Whoami_Call {
	_c.Call.Return(run)
	return _c
}
