// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockServiceConfig creates a new instance of MockServiceConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceConfig {
	mock := &MockServiceConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceConfig is an autogenerated mock type for the ServiceConfig type
type MockServiceConfig struct {
	mock.Mock
}

type MockServiceConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceConfig) EXPECT() *MockServiceConfig_Expecter {
	return &MockServiceConfig_Expecter{mock: &_m.Mock}
}

// Environment provides a mock function for the type MockServiceConfig
func (_mock *MockServiceConfig) Environment() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Environment")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockServiceConfig_Environment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Environment'
type MockServiceConfig_Environment_Call struct {
	*mock.Call
}

// Environment is a helper method to define mock.On call
func (_e *MockServiceConfig_Expecter) Environment() *MockServiceConfig_Environment_Call {
	return &MockServiceConfig_Environment_Call{Call: _e.mock.On("Environment")}
}

func (_c *MockServiceConfig_Environment_Call) Run(run func()) *MockServiceConfig_Environment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceConfig_Environment_Call) Return(s string) *MockServiceConfig_Environment_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockServiceConfig_Environment_Call) RunAndReturn(run func() string) *MockServiceConfig_Environment_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockServiceConfig
func (_mock *MockServiceConfig) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockServiceConfig_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockServiceConfig_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockServiceConfig_Expecter) Name() *MockServiceConfig_Name_Call {
	return &MockServiceConfig_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockServiceConfig_Name_Call) Run(run func()) *MockServiceConfig_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceConfig_Name_Call) Return(s string) *MockServiceConfig_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockServiceConfig_Name_Call) RunAndReturn(run func() string) *MockServiceConfig_Name_Call {
	_c.Call.Return(run)
	return _c
}
