// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRedisConfig creates a new instance of MockRedisConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedisConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedisConfig {
	mock := &MockRedisConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRedisConfig is an autogenerated mock type for the RedisConfig type
type MockRedisConfig struct {
	mock.Mock
}

type MockRedisConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedisConfig) EXPECT() *MockRedisConfig_Expecter {
	return &MockRedisConfig_Expecter{mock: &_m.Mock}
}

// Address provides a mock function for the type MockRedisConfig
func (_mock *MockRedisConfig) Address() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRedisConfig_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type MockRedisConfig_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *MockRedisConfig_Expecter) Address() *MockRedisConfig_Address_Call {
	return &MockRedisConfig_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *MockRedisConfig_Address_Call) Run(run func()) *MockRedisConfig_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRedisConfig_Address_Call) Return(s string) *MockRedisConfig_Address_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRedisConfig_Address_Call) RunAndReturn(run func() string) *MockRedisConfig_Address_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockRedisConfig
func (_mock *MockRedisConfig) DB() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockRedisConfig_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockRedisConfig_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockRedisConfig_Expecter) DB() *MockRedisConfig_DB_Call {
	return &MockRedisConfig_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockRedisConfig_DB_Call) Run(run func()) *MockRedisConfig_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRedisConfig_DB_Call) Return(n int) *MockRedisConfig_DB_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockRedisConfig_DB_Call) RunAndReturn(run func() int) *MockRedisConfig_DB_Call {
	_c.Call.Return(run)
	return _c
}

// Password provides a mock function for the type MockRedisConfig
func (_mock *MockRedisConfig) Password() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Password")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRedisConfig_Password_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Password'
type MockRedisConfig_Password_Call struct {
	*mock.Call
}

// Password is a helper method to define mock.On call
func (_e *MockRedisConfig_Expecter) Password() *MockRedisConfig_Password_Call {
	return &MockRedisConfig_Password_Call{Call: _e.mock.On("Password")}
}

func (_c *MockRedisConfig_Password_Call) Run(run func()) *MockRedisConfig_Password_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRedisConfig_Password_Call) Return(s string) *MockRedisConfig_Password_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRedisConfig_Password_Call) RunAndReturn(run func() string) *MockRedisConfig_Password_Call {
	_c.Call.Return(run)
	return _c
}
