// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIamServiceConfig creates a new instance of MockIamServiceConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIamServiceConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIamServiceConfig {
	mock := &MockIamServiceConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIamServiceConfig is an autogenerated mock type for the IamServiceConfig type
type MockIamServiceConfig struct {
	mock.Mock
}

type MockIamServiceConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIamServiceConfig) EXPECT() *MockIamServiceConfig_Expecter {
	return &MockIamServiceConfig_Expecter{mock: &_m.Mock}
}

// Address provides a mock function for the type MockIamServiceConfig
func (_mock *MockIamServiceConfig) Address() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIamServiceConfig_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type MockIamServiceConfig_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *MockIamServiceConfig_Expecter) Address() *MockIamServiceConfig_Address_Call {
	return &MockIamServiceConfig_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *MockIamServiceConfig_Address_Call) Run(run func()) *MockIamServiceConfig_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIamServiceConfig_Address_Call) Return(s string) *MockIamServiceConfig_Address_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIamServiceConfig_Address_Call) RunAndReturn(run func() string) *MockIamServiceConfig_Address_Call {
	_c.Call.Return(run)
	return _c
}
