// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/Reensef/go-microservices-course/iam/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Create(ctx context.Context, userUuid string, ttl time.Duration) (*model.Session, error) {
	ret := _mock.Called(ctx, userUuid, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (*model.Session, error)); ok {
		return returnFunc(ctx, userUuid, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) *model.Session); ok {
		r0 = returnFunc(ctx, userUuid, ttl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, userUuid, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userUuid string
//   - ttl time.Duration
func (_e *MockSessionRepository_Expecter) Create(ctx interface{}, userUuid interface{}, ttl interface{}) *MockSessionRepository_Create_Call {
	return &MockSessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, userUuid, ttl)}
}

func (_c *MockSessionRepository_Create_Call) Run(run func(ctx context.Context, userUuid string, ttl time.Duration)) *MockSessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Create_Call) Return(session *model.Session, err error) *MockSessionRepository_Create_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, userUuid string, ttl time.Duration) (*model.Session, error)) *MockSessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUUID provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) GetByUUID(ctx context.Context, sessionUuid string) (*model.Session, error) {
	ret := _mock.Called(ctx, sessionUuid)

	if len(ret) == 0 {
		panic("no return value specified for GetByUUID")
	}

	var r0 *model.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Session, error)); ok {
		return returnFunc(ctx, sessionUuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Session); ok {
		r0 = returnFunc(ctx, sessionUuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionUuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_GetByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUUID'
type MockSessionRepository_GetByUUID_Call struct {
	*mock.Call
}

// GetByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionUuid string
func (_e *MockSessionRepository_Expecter) GetByUUID(ctx interface{}, sessionUuid interface{}) *MockSessionRepository_GetByUUID_Call {
	return &MockSessionRepository_GetByUUID_Call{Call: _e.mock.On("GetByUUID", ctx, sessionUuid)}
}

func (_c *MockSessionRepository_GetByUUID_Call) Run(run func(ctx context.Context, sessionUuid string)) *MockSessionRepository_GetByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_GetByUUID_Call) Return(session *model.Session, err error) *MockSessionRepository_GetByUUID_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepository_GetByUUID_Call) RunAndReturn(run func(ctx context.Context, sessionUuid string) (*model.Session, error)) *MockSessionRepository_GetByUUID_Call {
	_c.Call.Return(run)
	return _c
}
