// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Reensef/go-microservices-course/iam/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Create(ctx context.Context, info *model.UserRegistrationInfo, passwordHash string) (*model.User, error) {
	ret := _mock.Called(ctx, info, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.UserRegistrationInfo, string) (*model.User, error)); ok {
		return returnFunc(ctx, info, passwordHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.UserRegistrationInfo, string) *model.User); ok {
		r0 = returnFunc(ctx, info, passwordHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.UserRegistrationInfo, string) error); ok {
		r1 = returnFunc(ctx, info, passwordHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - info *model.UserRegistrationInfo
//   - passwordHash string
func (_e *MockUserRepository_Expecter) Create(ctx interface{}, info interface{}, passwordHash interface{}) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, info, passwordHash)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(ctx context.Context, info *model.UserRegistrationInfo, passwordHash string)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.UserRegistrationInfo
		if args[1] != nil {
			arg1 = args[1].(*model.UserRegistrationInfo)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(user *model.User, err error) *MockUserRepository_Create_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(ctx context.Context, info *model.UserRegistrationInfo, passwordHash string) (*model.User, error)) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUUID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetByUUID(ctx context.Context, userUuid string) (*model.User, error) {
	ret := _mock.Called(ctx, userUuid)

	if len(ret) == 0 {
		panic("no return value specified for GetByUUID")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return returnFunc(ctx, userUuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = returnFunc(ctx, userUuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userUuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUUID'
type MockUserRepository_GetByUUID_Call struct {
	*mock.Call
}

// GetByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - userUuid string
func (_e *MockUserRepository_Expecter) GetByUUID(ctx interface{}, userUuid interface{}) *MockUserRepository_GetByUUID_Call {
	return &MockUserRepository_GetByUUID_Call{Call: _e.mock.On("GetByUUID", ctx, userUuid)}
}

func (_c *MockUserRepository_GetByUUID_Call) Run(run func(ctx context.Context, userUuid string)) *MockUserRepository_GetByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetByUUID_Call) Return(user *model.User, err error) *MockUserRepository_GetByUUID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetByUUID_Call) RunAndReturn(run func(ctx context.Context, userUuid string) (*model.User, error)) *MockUserRepository_GetByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredentialsByLogin provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetCredentialsByLogin(ctx context.Context, login string) (*model.User, string, error) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetCredentialsByLogin")
	}

	var r0 *model.User
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.User, string, error)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = returnFunc(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, login)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, login)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserRepository_GetCredentialsByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredentialsByLogin'
type MockUserRepository_GetCredentialsByLogin_Call struct {
	*mock.Call
}

// GetCredentialsByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockUserRepository_Expecter) GetCredentialsByLogin(ctx interface{}, login interface{}) *MockUserRepository_GetCredentialsByLogin_Call {
	return &MockUserRepository_GetCredentialsByLogin_Call{Call: _e.mock.On("GetCredentialsByLogin", ctx, login)}
}

func (_c *MockUserRepository_GetCredentialsByLogin_Call) Run(run func(ctx context.Context, login string)) *MockUserRepository_GetCredentialsByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetCredentialsByLogin_Call) Return(user *model.User, s string, err error) *MockUserRepository_GetCredentialsByLogin_Call {
	_c.Call.Return(user, s, err)
	return _c
}

func (_c *MockUserRepository_GetCredentialsByLogin_Call) RunAndReturn(run func(ctx context.Context, login string) (*model.User, string, error)) *MockUserRepository_GetCredentialsByLogin_Call {
	_c.Call.Return(run)
	return _c
}
