// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderProducerConfig creates a new instance of MockOrderProducerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderProducerConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderProducerConfig {
	mock := &MockOrderProducerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderProducerConfig is an autogenerated mock type for the OrderProducerConfig type
type MockOrderProducerConfig struct {
	mock.Mock
}

type MockOrderProducerConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderProducerConfig) EXPECT() *MockOrderProducerConfig_Expecter {
	return &MockOrderProducerConfig_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockOrderProducerConfig
func (_mock *MockOrderProducerConfig) Config() *sarama.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *sarama.Config
	if returnFunc, ok := ret.Get(0).(func() *sarama.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sarama.Config)
		}
	}
	return r0
}

// MockOrderProducerConfig_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockOrderProducerConfig_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockOrderProducerConfig_Expecter) Config() *MockOrderProducerConfig_Config_Call {
	return &MockOrderProducerConfig_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockOrderProducerConfig_Config_Call) Run(run func()) *MockOrderProducerConfig_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderProducerConfig_Config_Call) Return(config *sarama.Config) *MockOrderProducerConfig_Config_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *MockOrderProducerConfig_Config_Call) RunAndReturn(run func() *sarama.Config) *MockOrderProducerConfig_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Topic provides a mock function for the type MockOrderProducerConfig
func (_mock *MockOrderProducerConfig) Topic() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOrderProducerConfig_Topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topic'
type MockOrderProducerConfig_Topic_Call struct {
	*mock.Call
}

// Topic is a helper method to define mock.On call
func (_e *MockOrderProducerConfig_Expecter) Topic() *MockOrderProducerConfig_Topic_Call {
	return &MockOrderProducerConfig_Topic_Call{Call: _e.mock.On("Topic")}
}

func (_c *MockOrderProducerConfig_Topic_Call) Run(run func()) *MockOrderProducerConfig_Topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderProducerConfig_Topic_Call) Return(s string) *MockOrderProducerConfig_Topic_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOrderProducerConfig_Topic_Call) RunAndReturn(run func() string) *MockOrderProducerConfig_Topic_Call {
	_c.Call.Return(run)
	return _c
}
