// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSqlMigratorConfig creates a new instance of MockSqlMigratorConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSqlMigratorConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSqlMigratorConfig {
	mock := &MockSqlMigratorConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSqlMigratorConfig is an autogenerated mock type for the SqlMigratorConfig type
type MockSqlMigratorConfig struct {
	mock.Mock
}

type MockSqlMigratorConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSqlMigratorConfig) EXPECT() *MockSqlMigratorConfig_Expecter {
	return &MockSqlMigratorConfig_Expecter{mock: &_m.Mock}
}

// MigrationsDir provides a mock function for the type MockSqlMigratorConfig
func (_mock *MockSqlMigratorConfig) MigrationsDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MigrationsDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSqlMigratorConfig_MigrationsDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MigrationsDir'
type MockSqlMigratorConfig_MigrationsDir_Call struct {
	*mock.Call
}

// MigrationsDir is a helper method to define mock.On call
func (_e *MockSqlMigratorConfig_Expecter) MigrationsDir() *MockSqlMigratorConfig_MigrationsDir_Call {
	return &MockSqlMigratorConfig_MigrationsDir_Call{Call: _e.mock.On("MigrationsDir")}
}

func (_c *MockSqlMigratorConfig_MigrationsDir_Call) Run(run func()) *MockSqlMigratorConfig_MigrationsDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSqlMigratorConfig_MigrationsDir_Call) Return(s string) *MockSqlMigratorConfig_MigrationsDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSqlMigratorConfig_MigrationsDir_Call) RunAndReturn(run func() string) *MockSqlMigratorConfig_MigrationsDir_Call {
	_c.Call.Return(run)
	return _c
}
