// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentClientConfig creates a new instance of MockPaymentClientConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentClientConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentClientConfig {
	mock := &MockPaymentClientConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentClientConfig is an autogenerated mock type for the PaymentClientConfig type
type MockPaymentClientConfig struct {
	mock.Mock
}

type MockPaymentClientConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentClientConfig) EXPECT() *MockPaymentClientConfig_Expecter {
	return &MockPaymentClientConfig_Expecter{mock: &_m.Mock}
}

// Address provides a mock function for the type MockPaymentClientConfig
func (_mock *MockPaymentClientConfig) Address() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPaymentClientConfig_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type MockPaymentClientConfig_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *MockPaymentClientConfig_Expecter) Address() *MockPaymentClientConfig_Address_Call {
	return &MockPaymentClientConfig_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *MockPaymentClientConfig_Address_Call) Run(run func()) *MockPaymentClientConfig_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPaymentClientConfig_Address_Call) Return(s string) *MockPaymentClientConfig_Address_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPaymentClientConfig_Address_Call) RunAndReturn(run func() string) *MockPaymentClientConfig_Address_Call {
	_c.Call.Return(run)
	return _c
}
