services:
  notification:
    build:
      # Контекст должен быть корнем проекта, поэтому поднимаемся на три уровня
      context: ./../../..
      dockerfile: deploy/docker/notification/Dockerfile
      platforms:
        - linux/amd64

    image: notification-service:v0.0.1

    env_file:
      - ./.env

    restart: unless-stopped

    networks:
      - common

networks:
  common:
    external: true