// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// NewMockShipProducerConfig creates a new instance of MockShipProducerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShipProducerConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShipProducerConfig {
	mock := &MockShipProducerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShipProducerConfig is an autogenerated mock type for the ShipProducerConfig type
type MockShipProducerConfig struct {
	mock.Mock
}

type MockShipProducerConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShipProducerConfig) EXPECT() *MockShipProducerConfig_Expecter {
	return &MockShipProducerConfig_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockShipProducerConfig
func (_mock *MockShipProducerConfig) Config() *sarama.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *sarama.Config
	if returnFunc, ok := ret.Get(0).(func() *sarama.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sarama.Config)
		}
	}
	return r0
}

// MockShipProducerConfig_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockShipProducerConfig_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockShipProducerConfig_Expecter) Config() *MockShipProducerConfig_Config_Call {
	return &MockShipProducerConfig_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockShipProducerConfig_Config_Call) Run(run func()) *MockShipProducerConfig_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockShipProducerConfig_Config_Call) Return(config *sarama.Config) *MockShipProducerConfig_Config_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *MockShipProducerConfig_Config_Call) RunAndReturn(run func() *sarama.Config) *MockShipProducerConfig_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Topic provides a mock function for the type MockShipProducerConfig
func (_mock *MockShipProducerConfig) Topic() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockShipProducerConfig_Topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topic'
type MockShipProducerConfig_Topic_Call struct {
	*mock.Call
}

// Topic is a helper method to define mock.On call
func (_e *MockShipProducerConfig_Expecter) Topic() *MockShipProducerConfig_Topic_Call {
	return &MockShipProducerConfig_Topic_Call{Call: _e.mock.On("Topic")}
}

func (_c *MockShipProducerConfig_Topic_Call) Run(run func()) *MockShipProducerConfig_Topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockShipProducerConfig_Topic_Call) Return(s string) *MockShipProducerConfig_Topic_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockShipProducerConfig_Topic_Call) RunAndReturn(run func() string) *MockShipProducerConfig_Topic_Call {
	_c.Call.Return(run)
	return _c
}
