// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTracingConfig creates a new instance of MockTracingConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTracingConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTracingConfig {
	mock := &MockTracingConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTracingConfig is an autogenerated mock type for the TracingConfig type
type MockTracingConfig struct {
	mock.Mock
}

type MockTracingConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTracingConfig) EXPECT() *MockTracingConfig_Expecter {
	return &MockTracingConfig_Expecter{mock: &_m.Mock}
}

// CollectorEndpoint provides a mock function for the type MockTracingConfig
func (_mock *MockTracingConfig) CollectorEndpoint() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CollectorEndpoint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTracingConfig_CollectorEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectorEndpoint'
type MockTracingConfig_CollectorEndpoint_Call struct {
	*mock.Call
}

// CollectorEndpoint is a helper method to define mock.On call
func (_e *MockTracingConfig_Expecter) CollectorEndpoint() *MockTracingConfig_CollectorEndpoint_Call {
	return &MockTracingConfig_CollectorEndpoint_Call{Call: _e.mock.On("CollectorEndpoint")}
}

func (_c *MockTracingConfig_CollectorEndpoint_Call) Run(run func()) *MockTracingConfig_CollectorEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTracingConfig_CollectorEndpoint_Call) Return(s string) *MockTracingConfig_CollectorEndpoint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTracingConfig_CollectorEndpoint_Call) RunAndReturn(run func() string) *MockTracingConfig_CollectorEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceVersion provides a mock function for the type MockTracingConfig
func (_mock *MockTracingConfig) ServiceVersion() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServiceVersion")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTracingConfig_ServiceVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceVersion'
type MockTracingConfig_ServiceVersion_Call struct {
	*mock.Call
}

// ServiceVersion is a helper method to define mock.On call
func (_e *MockTracingConfig_Expecter) ServiceVersion() *MockTracingConfig_ServiceVersion_Call {
	return &MockTracingConfig_ServiceVersion_Call{Call: _e.mock.On("ServiceVersion")}
}

func (_c *MockTracingConfig_ServiceVersion_Call) Run(run func()) *MockTracingConfig_ServiceVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTracingConfig_ServiceVersion_Call) Return(s string) *MockTracingConfig_ServiceVersion_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTracingConfig_ServiceVersion_Call) RunAndReturn(run func() string) *MockTracingConfig_ServiceVersion_Call {
	_c.Call.Return(run)
	return _c
}
