// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIAMClientConfig creates a new instance of MockIAMClientConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAMClientConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAMClientConfig {
	mock := &MockIAMClientConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAMClientConfig is an autogenerated mock type for the IAMClientConfig type
type MockIAMClientConfig struct {
	mock.Mock
}

type MockIAMClientConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAMClientConfig) EXPECT() *MockIAMClientConfig_Expecter {
	return &MockIAMClientConfig_Expecter{mock: &_m.Mock}
}

// Address provides a mock function for the type MockIAMClientConfig
func (_mock *MockIAMClientConfig) Address() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIAMClientConfig_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type MockIAMClientConfig_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *MockIAMClientConfig_Expecter) Address() *MockIAMClientConfig_Address_Call {
	return &MockIAMClientConfig_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *MockIAMClientConfig_Address_Call) Run(run func()) *MockIAMClientConfig_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIAMClientConfig_Address_Call) Return(s string) *MockIAMClientConfig_Address_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIAMClientConfig_Address_Call) RunAndReturn(run func() string) *MockIAMClientConfig_Address_Call {
	_c.Call.Return(run)
	return _c
}
