// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConsumer creates a new instance of MockConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumer {
	mock := &MockConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConsumer is an autogenerated mock type for the Consumer type
type MockConsumer struct {
	mock.Mock
}

type MockConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumer) EXPECT() *MockConsumer_Expecter {
	return &MockConsumer_Expecter{mock: &_m.Mock}
}

// RunConsumer provides a mock function for the type MockConsumer
func (_mock *MockConsumer) RunConsumer(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RunConsumer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConsumer_RunConsumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunConsumer'
type MockConsumer_RunConsumer_Call struct {
	*mock.Call
}

// RunConsumer is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConsumer_Expecter) RunConsumer(ctx interface{}) *MockConsumer_RunConsumer_Call {
	return &MockConsumer_RunConsumer_Call{Call: _e.mock.On("RunConsumer", ctx)}
}

func (_c *MockConsumer_RunConsumer_Call) Run(run func(ctx context.Context)) *MockConsumer_RunConsumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConsumer_RunConsumer_Call) Return(err error) *MockConsumer_RunConsumer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConsumer_RunConsumer_Call) RunAndReturn(run func(ctx context.Context) error) *MockConsumer_RunConsumer_Call {
	_c.Call.Return(run)
	return _c
}
