services:
  order:
    build:
      # Контекст должен быть корнем проекта, поэтому поднимаемся на три уровня
      context: ./../../..
      dockerfile: deploy/docker/order/Dockerfile
      platforms:
        - linux/amd64

    # container_name: order-service # Имя контейнера приложения
    image: order-service:v1.0.0

    ports:
      - "127.0.0.1:${HTTP_PORT}:${HTTP_PORT}" # Публикуем только на localhost хоста; порт совпадает с тем, что слушает приложение
    env_file:
      - ./.env

    restart: unless-stopped

    networks:
      - common


networks:
  common:
    external: true