// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockShipConsumer creates a new instance of MockShipConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShipConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShipConsumer {
	mock := &MockShipConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShipConsumer is an autogenerated mock type for the ShipConsumer type
type MockShipConsumer struct {
	mock.Mock
}

type MockShipConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShipConsumer) EXPECT() *MockShipConsumer_Expecter {
	return &MockShipConsumer_Expecter{mock: &_m.Mock}
}

// RunConsumer provides a mock function for the type MockShipConsumer
func (_mock *MockShipConsumer) RunConsumer(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RunConsumer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipConsumer_RunConsumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunConsumer'
type MockShipConsumer_RunConsumer_Call struct {
	*mock.Call
}

// RunConsumer is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockShipConsumer_Expecter) RunConsumer(ctx interface{}) *MockShipConsumer_RunConsumer_Call {
	return &MockShipConsumer_RunConsumer_Call{Call: _e.mock.On("RunConsumer", ctx)}
}

func (_c *MockShipConsumer_RunConsumer_Call) Run(run func(ctx context.Context)) *MockShipConsumer_RunConsumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockShipConsumer_RunConsumer_Call) Return(err error) *MockShipConsumer_RunConsumer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipConsumer_RunConsumer_Call) RunAndReturn(run func(ctx context.Context) error) *MockShipConsumer_RunConsumer_Call {
	_c.Call.Return(run)
	return _c
}
