services:
  inventory:
    build:
      # Контекст должен быть корнем проекта, поэтому поднимаемся на три уровня
      context: ./../../..
      dockerfile: deploy/docker/inventory/Dockerfile
      platforms:
        - linux/amd64

    image: inventory-service:v1.0.0

    env_file:
      - ./.env

    restart: unless-stopped

    networks:
      - common

networks:
  common:
    external: true