// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// APIV1OrdersOrderUUIDGet implements GET /api/v1/orders/{order_uuid} operation.
	//
	// Получение информации о заказе.
	//
	// GET /api/v1/orders/{order_uuid}
	APIV1OrdersOrderUUIDGet(ctx context.Context, params APIV1OrdersOrderUUIDGetParams) (APIV1OrdersOrderUUIDGetRes, error)
	// APIV1OrdersPost implements POST /api/v1/orders operation.
	//
	// Создание нового заказа.
	//
	// POST /api/v1/orders
	APIV1OrdersPost(ctx context.Context, req *CreateOrderRequest) (APIV1OrdersPostRes, error)
	// CandelOrder implements CandelOrder operation.
	//
	// Отмена заказа.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	CandelOrder(ctx context.Context, params CandelOrderParams) (CandelOrderRes, error)
	// PayOrder implements PayOrder operation.
	//
	// Оплата заказа.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (PayOrderRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
