// Code generated by ogen, DO NOT EDIT.
package order_v1

type APIV1OrdersOrderUUIDGetRes interface {
	aPIV1OrdersOrderUUIDGetRes()
}

type APIV1OrdersPostRes interface {
	aPIV1OrdersPostRes()
}

type CandelOrderRes interface {
	candelOrderRes()
}

type PayOrderRes interface {
	payOrderRes()
}
