// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APIV1OrdersOrderUUIDGet implements GET /api/v1/orders/{order_uuid} operation.
//
// Получение информации о заказе.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) APIV1OrdersOrderUUIDGet(ctx context.Context, params APIV1OrdersOrderUUIDGetParams) (r APIV1OrdersOrderUUIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1OrdersPost implements POST /api/v1/orders operation.
//
// Создание нового заказа.
//
// POST /api/v1/orders
func (UnimplementedHandler) APIV1OrdersPost(ctx context.Context, req *CreateOrderRequest) (r APIV1OrdersPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CandelOrder implements CandelOrder operation.
//
// Отмена заказа.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) CandelOrder(ctx context.Context, params CandelOrderParams) (r CandelOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PayOrder implements PayOrder operation.
//
// Оплата заказа.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (r PayOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
