// Code generated by ogen, DO NOT EDIT.

package order_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	APIV1OrdersOrderUUIDGetOperation OperationName = "APIV1OrdersOrderUUIDGet"
	APIV1OrdersPostOperation         OperationName = "APIV1OrdersPost"
	CandelOrderOperation             OperationName = "CandelOrder"
	PayOrderOperation                OperationName = "PayOrder"
)
